### ISSUE TITLE
Errors while setting up a new nightly runner

### ISSUE THREAD

**Issue by Naman-Priyadarshi** [pvlib-benchmarker/pvlib-benchmarks#1]
After following the steps given in the [Readme.md](https://github.com/pvlib-benchmarker/pvlib-benchmarks/blob/master/README.md), I got an error in step 10 i.e. Validate and build environments using `asv check`.

![image](https://user-images.githubusercontent.com/77211855/161012005-7e38dedd-82f6-4415-b6e2-45bd49945667.png)

----------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/77211855/161012093-f1bc809d-2908-4fa0-ab00-74b1fe741aee.png)

----------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/77211855/161012308-0092b95a-6501-418d-846e-90d70c3ac2f1.png)

----------------------------------------------------------------------------------------------------------------------------------------------

![image](https://user-images.githubusercontent.com/77211855/161012392-01990443-456c-41b0-adae-03a3cebdeecc.png)

----------------------------------------------------------------------------------------------------------------------------------------------

Versions:
asv = 0.4.2
python = 3.7.1
conda = 4.10.3
virtualenv 20.14.0

**Comment by Naman-Priyadarshi** [comment]
Sorry for pasting all the screenshots, I couldn't understand the error properly.

**Comment by kandersolar** [comment]
Hi @Naman-Priyadarshi, thanks for filing this issue.  Right now we run the benchmarks in two environements: one with python 3.6 and on with 3.8.  It looks like creating the 3.6 environment is what's failing on your computer.  Our benchmark server runs linux, so I'm not entirely surprised that it doesn't work on windows.  One quick fix just to get things working on your computer might be to disable the 3.6 environment by deleting/commenting out these lines in the configuration file: https://github.com/pvlib/pvlib-python/blob/master/benchmarks/asv.conf.json#L115-L125

Of course we should think about better fixes for the longer term.  A couple ideas:
- Fiddle with the package versions to find a combination that doesn't fail on Windows
- Stop benchmarking on python 3.6 (it's [reached EOL](https://devguide.python.org/#status-of-python-branches) anyway), and replace it with a newer version like 3.9 or 3.10

**Comment by Naman-Priyadarshi** [comment]
I removed the lines to disable the 3.6v environment but there's a new error now 
i.e.

![image](https://user-images.githubusercontent.com/77211855/161823257-db4118c3-0571-48d7-8fb0-4f082ad5363a.png)

**Comment by kandersolar** [comment]
Hmm, I'm not sure about that one.  It kind of looks like there's some artifact of an old build left over.  Can you locate that file and delete it?  Restarting your computer might help too, if it's something silly like an old process didn't close that file properly.  Otherwise I'm not sure what to suggest.

**Comment by Naman-Priyadarshi** [comment]
I located the file and deleted it, but I'm still getting the same error. (Restarted my computer too)

**Comment by Naman-Priyadarshi** [comment]
Should I try setting up the benchmark in linux?

**Comment by Naman-Priyadarshi** [comment]
Update: `asv check` ran successfully in Linux and gave the following output:

`· Discovering benchmarks`
`·· Creating conda environment for conda-py3.8-ephem-h5py-numba-numpy-pandas-scipy..............................................`
`·· Uninstalling from conda-py3.8-ephem-h5py-numba-numpy-pandas-scipy`
`·· Building 5cb695d2 <master> for conda-py3.8-ephem-h5py-numba-numpy-pandas-scipy..`
`·· Installing 5cb695d2 <master> into conda-py3.8-ephem-h5py-numba-numpy-pandas-scipy.`
`· Checking benchmarks`
`·· No problems found.`


But after running the next step i.e. `asv dev` there's an error


![Screenshot from 2022-04-07 02-00-41](https://user-images.githubusercontent.com/77211855/162065428-2bcf673a-c82e-4492-ba72-6aa5c4556c9b.png)

(also I have some suggestions for Readme.md)

**Comment by kandersolar** [comment]
Good progress!  Looks like the example benchmarks you're running are written for python 2.x, but you're running on 3.7, so no big surprise that it's failing.  I guess maybe you copied the example benchmarks from [here](https://asv.readthedocs.io/en/stable/using.html)?  Since the failures are in the benchmark code itself, it seems like ASV itself is working correctly, which is great!  FYI I just sent in this PR to update the asv docs to not use those old 2.x examples anymore: https://github.com/airspeed-velocity/asv/pull/1207

Anyway, instead of using those dummy example benchmarks, I guess the next step is to use the real pvlib benchmarks.  If you have the `pvlib-python` repository next to the `pvlib-benchmarks` repository, I think all you need to do is modify the configuration file to point to the real benchmarks location like how the nightly job script does it:

https://github.com/pvlib-benchmarker/pvlib-benchmarks/blob/68c11a57eb2619790ab0a797d52e427391c22983/cronjob.sh#L29-L32

So it should probably look like this:
```
"repo": "../pvlib-python",
...
"benchmark_dir": "../pvlib-python/benchmarks/benchmarks",
```

> I have some suggestions for Readme.md

A PR with improvements would be most welcome!  I originally wrote those instructions for myself in case we needed to switch machines at some point in the future.  I didn't really think anybody else would read them, and I've not had any reason to update them until now :)

**Comment by Naman-Priyadarshi** [comment]
The Benchmarks ran successfully! Thanks @kanderso-nrel
